# vim:ft=kitty

## name:     Ricepaper e-ink Dark
## author:   ValentimSts
## license:  MIT
## upstream: claude.ai/design Ricepaper - Arch Rice Design System (tokens/palette-eink.css)
## blurb:    Electronic paper, inverted: #333333 canvas, #cccccc text, muted Everforest accents.

# The basic colors
foreground              #cccccc
background              #333333
selection_foreground    #333333
selection_background    #cccccc

# Cursor colors
cursor                  #cccccc
cursor_text_color       #262626

# URL underline color when hovering with mouse
url_color               #7fbbb3

# Kitty window border colors
active_border_color     #cccccc
inactive_border_color   #686868
bell_border_color       #dbbc7f

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #262626
active_tab_background   #cccccc
inactive_tab_foreground #cccccc
inactive_tab_background #2c2c2c
tab_bar_background      #262626

# Colors for marks (marked text in the terminal)
mark1_foreground #333333
mark1_background #a9afd9
mark2_foreground #333333
mark2_background #c58bc0
mark3_foreground #333333
mark3_background #7fb0bb

# The 16 terminal colors

# black
color0 #4a4a4a
color8 #545454

# red
color1 #e67e80
color9 #e67e80

# green
color2  #a7c080
color10 #a7c080

# yellow
color3  #dbbc7f
color11 #dbbc7f

# blue
color4  #7fbbb3
color12 #7fbbb3

# magenta
color5  #d699b6
color13 #d699b6

# cyan
color6  #83c092
color14 #83c092

# white
color7  #c2c2c2
color15 #a4a4a4
