# vim:ft=kitty

## name:     Ricepaper e-ink Light
## author:   ValentimSts
## license:  MIT
## upstream: claude.ai/design Ricepaper - Arch Rice Design System (tokens/palette-eink.css)
## blurb:    Electronic paper: #cccccc paper, #333333 ink, muted Everforest accents.

# The basic colors
foreground              #333333
background              #cccccc
selection_foreground    #cccccc
selection_background    #474747

# Cursor colors
cursor                  #474747
cursor_text_color       #f0f0f0

# URL underline color when hovering with mouse
url_color               #3a94c5

# Kitty window border colors
active_border_color     #474747
inactive_border_color   #909090
bell_border_color       #dfa000

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #f0f0f0
active_tab_background   #474747
inactive_tab_foreground #333333
inactive_tab_background #c6c6c6
tab_bar_background      #c0c0c0

# Colors for marks (marked text in the terminal)
mark1_foreground #cccccc
mark1_background #7a88c4
mark2_foreground #cccccc
mark2_background #b95fa8
mark3_foreground #cccccc
mark3_background #2f86bb

# The 16 terminal colors

# black
color0 #aeaeae
color8 #a4a4a4

# red
color1 #f85552
color9 #f85552

# green
color2  #8da101
color10 #8da101

# yellow
color3  #dfa000
color11 #dfa000

# blue
color4  #3a94c5
color12 #3a94c5

# magenta
color5  #df69ba
color13 #df69ba

# cyan
color6  #35a77c
color14 #35a77c

# white
color7  #474747
color15 #545454
