# vim:ft=kitty

## name:     Orange Peel Dark
## author:   ValentimSts
## license:  MIT
## upstream: github.com/ValentimSts/dotfile/.config/color-schemes
## blurb:    A warm and mellow orange dark theme.

# The basic colors
foreground              #e6d5b8
background              #1b1e12
selection_foreground    #1b1e12
selection_background    #D3AB6A

# Cursor colors
cursor                  #e6d5b8
cursor_text_color       #1b1e12

# URL underline color when hovering with mouse
url_color               #e6d5b8

# Kitty window border colors
active_border_color     #AD905D
inactive_border_color   #968457
bell_border_color       #F9DE7C

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1b1e12
active_tab_background   #F1CB75
inactive_tab_foreground #e6d5b8
inactive_tab_background #968457
tab_bar_background      #1b1e12

# Colors for marks (marked text in the terminal)
mark1_foreground #1b1e12
mark1_background #D3AB6A
mark2_foreground #1b1e12
mark2_background #DEB168
mark3_foreground #1b1e12
mark3_background #F1CB75

# The 16 terminal colors

# black (Dark Olive)
color0 #1b1e12
color8 #a19580

# brown (Muted Brown)
color1 #968457
color9 #968457

# olive (Golden Olive)
color2  #AD905D
color10 #AD905D

# gold (Warm Gold)
color3  #D3AB6A
color11 #D3AB6A

# mustard (Dark Mustard)
color4  #DEB168
color12 #DEB168

# amber (Soft Amber)
color5  #F1CB75
color13 #F1CB75

# butter (Light Yellow)
color6  #F9DE7C
color14 #F9DE7C

# beige (Light Beige)
color7  #e6d5b8
color15 #e6d5b8

