# vim:ft=kitty

## name:     Orange Peel Light
## author:   ValentimSts
## license:  MIT
## upstream: github.com/ValentimSts/dotfile/.config/color-schemes
## blurb:    A warm and mellow orange light theme.

# The basic colors
foreground              #2E331E
background              #fdf8ed
selection_foreground    #fdf8ed
selection_background    #D3AB6A

# Cursor colors
cursor                  #2E331E
cursor_text_color       #fdf8ed

# URL underline color when hovering with mouse
url_color               #2E331E

# Kitty window border colors
active_border_color     #AD905D
inactive_border_color   #968457
bell_border_color       #F9DE7C

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #fdf8ed
active_tab_background   #F1CB75
inactive_tab_foreground #2E331E
inactive_tab_background #968457
tab_bar_background      #fdf8ed

# Colors for marks (marked text in the terminal)
mark1_foreground #fdf8ed
mark1_background #D3AB6A
mark2_foreground #fdf8ed
mark2_background #DEB168
mark3_foreground #fdf8ed
mark3_background #F1CB75

# The 16 terminal colors

# black (Light Beige)
color0 #fdf8ed
color8 #927f53

# brown (Muted Brown)
color1 #968457
color9 #968457

# olive (Golden Olive)
color2  #AD905D
color10 #AD905D

# gold (Warm Gold)
color3  #D3AB6A
color11 #D3AB6A

# mustard (Dark Mustard)
color4  #DEB168
color12 #DEB168

# amber (Soft Amber)
color5  #F1CB75
color13 #F1CB75

# butter (Light Yellow)
color6  #F9DE7C
color14 #F9DE7C

# beige (Dark Olive)
color7  #2E331E
color15 #2E331E

