# ---------------------------------------
#
#  ██╗  ██╗██╗████████╗████████╗██╗   ██╗
#  ██║ ██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  █████╔╝ ██║   ██║      ██║    ╚████╔╝ 
#  ██╔═██╗ ██║   ██║      ██║     ╚██╔╝  
#  ██║  ██╗██║   ██║      ██║      ██║   
#  ╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝   
#
# ---------------------------------------
# 
# The code bellow is equivalent to:
#  - 'globinclude configs/*.conf'.
#
# However, I like being verbose...and this
# file felt too empty with only a single
# line.
#

include configs/theme.conf
include configs/typography.conf
include configs/keymaps.conf
include configs/settings.conf
map shift+enter send_text all \e\r
